// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devgoorita/golang-basecode/internal/controllers"
	"github.com/devgoorita/golang-basecode/internal/repositories"
	"github.com/devgoorita/golang-basecode/internal/routers"
	"github.com/devgoorita/golang-basecode/internal/services"
	"github.com/devgoorita/golang-basecode/pkg"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializedServer() *routers.Routes {
	db := pkg.NewDB()
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userController := controllers.NewUserController(userService)
	authenticationController := controllers.NewAuthenticationController(userService)
	routes := routers.NewRoutes(userController, authenticationController)
	return routes
}

// injector.go:

var userSet = wire.NewSet(repositories.NewUserRepository, services.NewUserService, controllers.NewUserController)
